import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Toaster } from "@/components/ui/toaster";
import { auth } from '@/auth';
import { AuthButtons } from '@/features/auth';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <header className="flex items-center justify-between border-b px-6 py-3">
            <h1 className="text-lg font-semibold">UnixDox</h1>
            <AuthButtons authenticated={!!session?.user} />
          </header>
          <main>{children}</main>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
